---
params:
  blobstore_s3_region: (( param "Specify the AWS region for your Cloud Controller blobstore" ))

meta:
  blobstore_config:
    blobstore_type: fog
    fog_connection: &fog_connection
      aws_access_key_id:     (( vault meta.vault "/blobstore:aws_access_key" ))
      aws_secret_access_key: (( vault meta.vault "/blobstore:aws_access_secret" ))
      provider: AWS
      region: (( grab params.blobstore_s3_region ))
