---
meta:
  blobstore_config:
    blobstore_type: fog
    fog_connection:
      provider: Google
      google_project:         (( vault meta.vault "/blobstore:gcp_project_name" ))
      google_client_email:    (( vault meta.vault "/blobstore:gcp_client_email" ))
      google_json_key_string: (( vault meta.vault "/blobstore:gcp_json_key" ))
