---
meta:
  blobstore_config:
    blobstore_type: fog
    fog_connection:
      provider: Google
      google_storage_access_key_id:     (( vault meta.vault "/blobstore:gcp_sa_key" ))
      google_storage_secret_access_key: (( vault meta.vault "/blobstore:gcp_sa_secret" ))
