#!/usr/bin/env bash

set -e
set -o pipefail

pushd cf-deployment
  version=$(cat .git/ref)
popd

pushd git > /dev/null

  if [[ -z $(git config --global user.email) ]]; then
      git config --global user.email "ci@starkandwayne.com"
  fi
  if [[ -z $(git config --global user.name) ]]; then
      git config --global user.name "CI Bot"
  fi

  echo "CHECKING git status"
  git status

  echo "Bump CF deployment to $version"
  ../git-ci/ci/scripts/pull-upstream $version

  echo "recreate spec-test results to validate: the cf-deployment update "

  pushd spec > /dev/null
    # TODO: remove spec/{credhub,vault} if needed? because this will regenerate vault.
    rm -rf results/
    ginkgo
  popd

  git add cf-deployment
  git add spec/
  git commit -m "Update cf-deployment to $version"

popd > /dev/null
