---
instance_groups:
- name: bbs
  jobs:
    - name: consul_agent
      release: consul
      consumes:
        consul_common: {from: consul_common_link}
        consul_server: nil
        consul_client: {from: consul_client_link}

    - name: bbs
      release: diego
      properties:
        diego:
          bbs:
            active_key_label: key1
            encryption_keys:
              - label: key1
                passphrase: (( vault meta.vault "/diego/encryption_key:value" ))
            auctioneer:
              ca_cert: (( grab meta.certs.diego.ca ))
              .: (( inject meta.certs.diego.auctioneer.client ))
              require_tls: true
            ca_cert: (( grab meta.certs.diego.ca ))
            .: (( inject meta.certs.diego.bbs.server ))
            rep:
              ca_cert: (( grab meta.certs.diego.ca ))
              .: (( inject meta.certs.diego.rep.client ))
              require_tls: true
            sql:
              #no ssl to the sql backend
              db_driver: (( grab params.diegodb_scheme ))
              max_open_connections: 500
              db_connection_string: (( grab params.diegodb_connection_string ))
            # Etcd keys aren't actually used by diego (unless you're migrating off
            # etcd into a sql database), but for whatever reason they
            # don't have defaults in the BOSH Release and so we need to populate
            # them with garbage
            etcd:
              machines: []
              ca_cert: ""
              client_cert: ""
              client_key: ""

