---
instance_groups:
- name: cell
  jobs:
  - name: consul_agent
    release: consul
    consumes:
      consul_common: {from: consul_common_link}
      consul_server: nil
      consul_client: {from: consul_client_link}

  - { name: cflinuxfs2-rootfs-setup, release: cflinuxfs2 }

  - name: garden
    release: garden-runc
    properties:
      garden:
        default_container_grace_time: 0
        destroy_containers_on_start: true
        graph_cleanup_threshold_in_mb: 0
        cleanup_process_dirs_on_wait: true
        deny_networks:
        - 0.0.0.0/0
        persistent_image_list:
        - "/var/vcap/packages/cflinuxfs2/rootfs.tar"

  - name: rep
    release: diego
    properties:
      tls:
        ca_cert: (( grab meta.certs.diego.ca ))
        cert: (( grab meta.certs.diego.rep.server.server_cert ))
        key: (( grab meta.certs.diego.rep.server.server_key ))
      diego:
        ssl:
          skip_cert_verify: (( grab params.skip_ssl_validation ))
        rep:
          bbs:
            ca_cert: (( grab meta.certs.diego.ca ))
            .: (( inject meta.certs.diego.bbs.client ))
          enable_legacy_api_endpoints: false
          evacuation_timeout_in_seconds: 60
          listen_addr_admin: ~
          preloaded_rootfses:
          - cflinuxfs2:/var/vcap/packages/cflinuxfs2/rootfs.tar
          require_tls: true
          ca_cert: (( grab meta.certs.diego.ca ))
          .: (( inject meta.certs.diego.rep.server ))
