---
instance_groups:
- name: diego
  jobs:
  - name: consul_agent
    release: consul
    consumes:
      consul_common: {from: consul_common_link}
      consul_server: nil
      consul_client: {from: consul_client_link}

  - name: auctioneer
    release: diego
    properties:
      diego:
        auctioneer:
          bbs:
            ca_cert: (( grab meta.certs.diego.ca ))
            .: (( inject meta.certs.diego.bbs.client ))
          rep:
            ca_cert: (( grab meta.certs.diego.ca ))
            .: (( inject meta.certs.diego.rep.client ))

          ca_cert: (( grab meta.certs.diego.ca ))
          .: (( inject meta.certs.diego.auctioneer.server ))

  - name: tps
    release: capi
    properties:
      capi:
        tps:
          listener_enabled: false
          bbs:
            ca_cert: (( grab meta.certs.diego.ca ))
            .: (( inject meta.certs.diego.bbs.client ))
          cc:
            ca_cert: (( grab meta.certs.diego.ca ))
            .: (( inject meta.certs.diego.tps.client ))

  - name: cc_uploader
    release: capi
    properties:
      capi:
        cc_uploader:
          cc:
            ca_cert: (( grab meta.certs.diego.ca ))
            .: (( inject meta.certs.diego.cc_uploader.client ))
          mutual_tls:
            ca_cert: (( grab meta.certs.diego.ca ))
            .: (( inject meta.certs.diego.cc_uploader.server ))

  - name: route_emitter
    release: diego
    properties:
      diego:
        route_emitter:
          bbs:
            ca_cert: (( grab meta.certs.diego.ca ))
            .: (( inject meta.certs.diego.bbs.client ))
          healthcheck_address: 127.0.0.1:17012 # to avoid conflict colocating with stager
          uaa:
            ca_cert: (( grab meta.certs.uaa.ca ))
            client_secret: (( grab meta.uaa.tcp_emitter_secret ))