---
instance_groups:
  - name: nats
    jobs:
      - name: nats
        release: nats
        provides:
          nats: {as: nats, shared: true}
        properties:
          nats:
            debug: false
            trace: false
            monitor_port: 9222
            prof_port:    0
            port:         4222

            user:     nats_user
            password: (( vault meta.vault "/nats:password" ))
