#!/bin/bash

error() {
  echo "[1;31m[ERROR][0m $1"
  exit 1
}

# Check if version specified
version="${1:-}"
[[ -n "$version" ]] || error "Usage: $0 <version>"

#Config
upstream_name="cf-deployment"
upstream_path="https://github.com/cloudfoundry/${upstream_name}/archive/v${version}.tar.gz"
upstream_url="https://github.com/cloudfoundry/${upstream_name}/releases/tag/v${version}"
upstream_file="${upstream_name}-${version}.tar.gz"
upstream_dir="$upstream_name"
files=(
  cf-deployment.yml
  iaas-support
  operations
  LICENSE
  README.md
)

set -ue
# go to base directory
basepath="$( cd "$(dirname "$0")/../" >/dev/null 2>&1 ; pwd -P )"
cd "$basepath"
[[ -d "$upstream_dir" ]] || error "Could not find upstream directory '$upstream_dir' under base path $basepath"

workdir=$(mktemp -d 2>/dev/null || mktemp -d -t 'mytmpdir')
[[ -n "$workdir" ]] && [[ -d "$workdir" ]] || error "Failed to make work directory"

file="$workdir/$upstream_file"
echo "Fetching ${upstream_name} v${version} release from cloudfoundry Github organization}"

curl -sSL -o "$file" "$upstream_path" > /dev/null
if ! [[ -f "$file" ]] ; then
  error "Failed to download $upstream_name v$version -- cannot continue"
fi
topdir="$(tar -ztf "$file" | awk '{print $NF}' | cut -d'/' -f1 | uniq)"
if [[ $topdir != "${upstream_name}-$version" ]] ; then
  error "Downloaded $upstream_name v$version doesn't look like a valid release  -- cannot continue"
fi

pushd "$workdir" >/dev/null
echo "Extracting release v$version..."
tar -zxf "$file" || error "Unable to extract repository"
popd >/dev/null

rm -rf $upstream_dir
mkdir $upstream_dir
src="$workdir/${upstream_name}-$version"
for f in "${files[@]}" ; do
  cp -R "$src/$f" "${upstream_dir}/$f"
done

ts="$(date -u +"%Y-%b-%d %H:%M:%S %Z")"
cat > overlay/upstream_version.yml <<EOF
exodus:
  ${upstream_name}-version: $version
  ${upstream_name}-date:    $ts
  ${upstream_name}-url:     $upstream_url
EOF

rm -rf "$workdir"
echo "Done."
