#!/bin/bash
set -eu

SKIP_FRESH=${SKIP_FRESH:-"false"}
SKIP_DEPLOY=${SKIP_DEPLOY:-"false"}
SKIP_SMOKE_TESTS=${SKIP_SMOKE_TESTS:-"false"}
SKIP_CLEAN=${SKIP_CLEAN:-"false"}
DEPLOYMENT_NAMES=(${DEPLOYMENT_NAMES-"ci-baseline"})


header() {
	echo
	echo "###############################################"
	echo
	echo $*
	echo
}

cleanup() {
	for deployment in "$@"; do
		echo "> deleting ${deployment}"
		$BOSH -n -d "${deployment}" delete-deployment

		for disk in $($BOSH disks --orphaned | grep "${deployment}" | awk '{print $1}'); do
			echo "  - removing disk $disk"
			$BOSH -n delete-disk "$disk"
		done
	done
}

header "Checking previous deployments on ${BOSH_ENVIRONMENT}..."
$BOSH deployments

header "Cleaning up from any previous deployments (if necessary)..."
for DEPLOYMENT_NAME in $DEPLOYMENT_NAMES; do
  if [[ "$SKIP_FRESH" == "false" ]]; then
    cleanup ${DEPLOYMENT_NAME}-${KIT}

    # replace - with / for safe commands
    depname=${DEPLOYMENT_NAME//-//}
    safe rm -rf secret/${depname}/${KIT}
    safe ssh secret/${depname}/${KIT}/test-user

    credhub login --server $CREDHUB_URL --username $CREDHUB_USER --password $CREDHUB_PASSWORD --skip-tls-validation
    credhub delete -p /snw-genesis-ci-bosh/${DEPLOYMENT_NAME}-${KIT}/


  else
    echo "Skipping FRESH"
  fi

  if [[ "$SKIP_DEPLOY" == "false" ]]; then
    header "Deploying BASELINE environment to verify functionality..."
    cd dev
    # make sure hooks are executable before screaming at shipit for failing.
    genesis compile-kit --name $KIT -v 9.9.9 --force
    cd ..
    genesis add-secrets ${DEPLOYMENT_NAME}

    # get and upload stemcell version if needed (handled by bosh cli if version and name are supplied)
    stemcell_version=$(genesis manifest ${DEPLOYMENT_NAME} | spruce json | jq -r .stemcells[0].version)
    bosh upload-stemcell "https://bosh.io/d/stemcells/bosh-vsphere-esxi-ubuntu-xenial-go_agent?v=${stemcell_version}" --version ${stemcell_version} --name bosh-vsphere-esxi-ubuntu-xenial-go_agent

    genesis deploy -y ${DEPLOYMENT_NAME}
    $BOSH -d ${DEPLOYMENT_NAME}-${KIT} instances --ps
  fi

  if [[ "$SKIP_SMOKE_TESTS" == "false" ]]; then
    header "Validating BASELINE environment..."
    $BOSH -d ${DEPLOYMENT_NAME}-${KIT} run-errand smoke_tests
  else
      echo "Skipping smoke_tests"
  fi

  if [[ "$SKIP_CLEAN" == "false" ]]; then
    cleanup ${DEPLOYMENT_NAME}-${KIT}
  else
    echo "Skipping CLEANUP"
  fi
done