#!/bin/bash
set -eu

SKIP_FRESH=${SKIP_FRESH:-"false"}
SKIP_DEPLOY=${SKIP_DEPLOY:-"false"}
SKIP_SMOKE_TESTS=${SKIP_SMOKE_TESTS:-"false"}
SKIP_CLEAN=${SKIP_CLEAN:-"false"}

header() {
	echo
	echo "###############################################"
	echo
	echo $*
	echo
}

cleanup() {
	for deployment in "$@"; do
		echo "> deleting ${deployment}"
		$BOSH -n -d "${deployment}" delete-deployment

		for disk in $($BOSH disks --orphaned | grep "${deployment}" | awk '{print $1}'); do
			echo "  - removing disk $disk"
			$BOSH -n delete-disk "$disk"
		done
	done
}

header "Checking previous deployments on ${BOSH_ENVIRONMENT}..."
$BOSH deployments

header "Cleaning up from any previous deployments (if necessary)..."
if [[ "$SKIP_FRESH" == "false" ]]; then
  cleanup ci-baseline-${KIT}
  safe rm -rf secret/ci/baseline/${KIT}

  credhub login --server $CREDHUB_URL --username $CREDHUB_USER --password $CREDHUB_PASSWORD --skip-tls-validation
  credhub delete -p /snw-genesis-ci-bosh/ci-baseline-cf/

  safe ssh secret/ci/baseline/${KIT}/test-user
else
  echo "Skipping FRESH"
fi

if [[ "$SKIP_DEPLOY" == "false" ]]; then
  header "Deploying BASELINE environment to verify functionality..."
  cd dev
  # make sure hooks are executable before screaming at shipit for failing.
  genesis compile-kit --name $KIT -v 9.9.9 --force
  cd ..
  genesis add-secrets ci-baseline
  genesis deploy -y ci-baseline
  $BOSH -d ci-baseline-${KIT} instances --ps
fi

if [[ "$SKIP_SMOKE_TESTS" == "false" ]]; then
  header "Validating BASELINE environment..."
  $BOSH -d ci-baseline-${KIT} run-errand smoke_tests
else
    echo "Skipping smoke_tests"
fi

if [[ "$SKIP_CLEAN" == "false" ]]; then
  cleanup ci-baseline-${KIT}
else
  echo "Skipping CLEANUP"
fi