---
params:
  disable_tls_10: false
  disable_tls_11: false

instance_groups:
  - name: haproxy
    jobs:
      - name: haproxy
        properties:
          ha_proxy:
            disable_tls_10: (( grab params.disable_tls_10 ))
            disable_tls_11: (( grab params.disable_tls_11 ))

            ssl_pem: (( vault meta.vault "/haproxy/ssl:combined" ))
