---
params:
  internal_only_domains: []
  trusted_domain_cidrs: ""

  haproxy_instances: 2
  haproxy_vm_type:   small

instance_groups:
  - name: router
    vm_extensions: (( empty array ))
  - name: access
    vm_extensions: (( empty array ))

  - (( insert before "nats" ))
  - name: haproxy
    instances: (( grab params.haproxy_instances ))
    vm_type: (( grab params.haproxy_vm_type ))
    azs: (( grab params.availability_zones || meta.default.azs ))
    stemcell: default
    networks:
      - name: (( grab params.cf_edge_network ))
        static_ips: (( static_ips 10 11 12 13 14 ))

    vm_extensions:
      - cf-elb
      - ssh-elb

    jobs:
      - name: consul_agent
        release: consul
        consumes:
          consul_common: {from: consul_common_link}
          consul_server: nil
          consul_client: {from: consul_client_link}

      - name: haproxy
        release: haproxy
        properties:
          ha_proxy:
            backend_servers: (( grab instance_groups.router.networks[0].static_ips ))
            internal_only_domains: (( grab params.internal_only_domains ))
            trusted_domain_cidrs:  (( grab params.trusted_domain_cidrs ))
            ssl_pem: ~

            # haproxy is using links now for the ssh proxies
            tcp_link_port: 2222

releases:
  - name: haproxy
    version: 8.1.2
    sha1: 7dea39924dfb05175e2bb97bc9fa5034080dcc1b
    url: https://github.com/cloudfoundry-incubator/haproxy-boshrelease/releases/download/v8.1.2/haproxy-8.1.2.tgz
