---
params:
  internal_only_domains: []
  trusted_domain_cidrs: ~

  cf_lb_network: (( grab params.cf_edge_network ))

  haproxy_instances: 2
  haproxy_vm_type:   haproxy
  haproxy_ips:       (( param "Please specify the IP addresses for your load balancer instances" ))

instance_groups:
  - name: router
    vm_extensions: (( empty array ))

  - (( insert before "router" ))
  - name: haproxy
    instances: (( grab params.haproxy_instances ))
    vm_type:   (( grab params.haproxy_vm_type ))
    azs:       (( grab params.availability_zones || meta.default.azs ))

    stemcell: default
    networks:
      - name:       (( grab params.cf_lb_network ))
        static_ips: (( grab params.haproxy_ips ))

    vm_extensions:
      - cf-load-balanced

    jobs:
      - name: haproxy
        release: haproxy
        consumes:
          http_backend: { from: gorouter,  ip_addresses: true }
          tcp_backend:  { from: ssh-proxy, ip_addresses: true }

        properties:
          ha_proxy:
            internal_only_domains: (( grab params.internal_only_domains ))
            trusted_domain_cidrs:  (( grab params.trusted_domain_cidrs ))
            ssl_pem: ~

            # haproxy is using links now for the ssh proxies
            tcp_link_port: 2222

releases:
  - name:    haproxy
    version: "9.7.1"
    url:     (( concat "https://bosh.io/d/github.com/cloudfoundry-incubator/haproxy-boshrelease?v=" releases.haproxy.version ))
    sha1:    a5bc4f04f212a26bbe8f36f339a751d7773eb223
