---
- type: replace
  path: /instance_groups/name=bits/jobs/name=bits-service/properties/bits-service/app_stash
  value:
    directory_key: ((resource_directory_key))
    fog_connection: &fog_connection
      provider: Google
      google_storage_access_key_id: ((blobstore_access_key_id))
      google_storage_secret_access_key: ((blobstore_secret_access_key))

- type: replace
  path: /instance_groups/name=bits/jobs/name=bits-service/properties/bits-service/buildpacks
  value:
    directory_key: ((buildpack_directory_key))
    fog_connection: *fog_connection
- type: replace
  path: /instance_groups/name=bits/jobs/name=bits-service/properties/bits-service/droplets
  value:
    directory_key: ((droplet_directory_key))
    fog_connection: *fog_connection
- type: replace
  path: /instance_groups/name=bits/jobs/name=bits-service/properties/bits-service/packages
  value:
    directory_key: ((app_package_directory_key))
    fog_connection: *fog_connection
