---
- type: replace
  path: /instance_groups/name=bits/jobs/name=bits-service/properties/bits-service/app_stash
  value:
    directory_key: ((resource_directory_key))
    fog_connection: &fog_connection
      provider: Google
      google_project: ((gcs_project))
      google_client_email: ((gcs_service_account_email))
      google_json_key_string: ((gcs_service_account_json_key))

- type: replace
  path: /instance_groups/name=bits/jobs/name=bits-service/properties/bits-service/buildpacks
  value:
    directory_key: ((buildpack_directory_key))
    fog_connection: *fog_connection
- type: replace
  path: /instance_groups/name=bits/jobs/name=bits-service/properties/bits-service/droplets
  value:
    directory_key: ((droplet_directory_key))
    fog_connection: *fog_connection
- type: replace
  path: /instance_groups/name=bits/jobs/name=bits-service/properties/bits-service/packages
  value:
    directory_key: ((app_package_directory_key))
    fog_connection: *fog_connection
