---
meta:
  external_db_username: (( vault meta.vault "/external_db:username" ))
  external_db_password: (( vault meta.vault "/external_db:password" ))
  external_db_scheme:   mysql
  external_db_port:     3306

params:
  external_db_host: (( param "Please provide the hostname / IP of your external MySQL database instance" ))

  uaadb_host:     (( grab meta.external_db_host ))
  uaadb_user:     (( grab meta.external_db_username ))
  uaadb_password: (( grab meta.external_db_password ))
  uaadb_scheme:   (( grab meta.external_db_scheme ))
  uaadb_port:     (( grab meta.external_db_port ))

  ccdb_host:     (( grab meta.external_db_host ))
  ccdb_user:     (( grab meta.external_db_username ))
  ccdb_password: (( grab meta.external_db_password ))
  ccdb_scheme:   (( grab meta.external_db_scheme ))
  ccdb_port:     (( grab meta.external_db_port ))

  diegodb_host:     (( grab meta.external_db_host ))
  diegodb_user:     (( grab meta.external_db_username ))
  diegodb_password: (( grab meta.external_db_password ))
  diegodb_scheme:   (( grab meta.external_db_scheme ))
  diegodb_port:     (( grab meta.external_db_port ))

  diegodb_connection_string: (( concat params.diegodb_user ":" params.diegodb_password "@tcp(" params.diegodb_host ":" params.diegodb_port ")/" params.diegodb_name ))
