z1_cluster: 
z1_resource_pool: 
z1_datacenter_name: 
z1_network_name: 
z1_network_gateway: 
z1_network_dns_array: []
z1_network_range: 
z1_network_reserved_array: []

z2_cluster: 
z2_resource_pool: 
z2_datacenter_name: 
z2_network_name: 
z2_network_gateway: 
z2_network_dns_array: []
z2_network_range: 
z2_network_reserved_array: []

z3_cluster: 
z3_resource_pool: 
z3_datacenter_name: 
z3_network_name: 
z3_network_gateway: 
z3_network_dns_array: []
z3_network_range: 
z3_network_reserved_array: []