--- # overrides: basic overrides for genesis compatibility
exodus:
  admin_username:          admin
  admin_password:          ((cf_admin_password))
  base_domain:             (( grab params.base_domain ))
  system_domain:           (( grab params.system_domain ))
  app_domains:             (( grab params.app_domains ))
  apps_domain:             (( grab params.apps_domain ))
  api_domain:              (( concat "api." params.system_domain ))

  edge_network:            (( grab params.cf_edge_network || params.network ))
  tcp_edge_network:        (( grab params.cf_tcp_edge_network || params.cf_edge_network || params.network ))
  core_network:            (( grab params.cf_core_network || params.network ))
  runtime_network:         (( grab params.cf_runtime_network || params.network ))
  db_network:              (( grab params.cf_db_network || params.cf_core_network || params.network ))

  vaulted_uaa_clients:     (( concat meta.vault "/uaa/client_secrets:firehose" ))

  system_org:   system
  system_space: system

# BOSH Variables - used to populate ((variables))
bosh-variables:
  system_domain:   (( grab params.system_domain ))
  deployment_name: (( grab name ))
  network_name:    (( grab params.network ))

meta:
  app_domains:
    - ((system_domain))
  default_apps_domains: (( grab params.apps_domains || meta.app_domains ))
  internal_app_domains: []
  default_azs: [z1, z2]
  azs: (( grab params.availability_zones || meta.default_azs ))

  database_defaults:
    cloud_controller:     {name: cloud_controller,     user: cloud_controller}
    uaa:                  {name: uaa,                  user: uaa}
    diego:                {name: diego,                user: diego}
    routing_api:          {name: routing-api,          user: routing-api}
    network_policy:       {name: network_policy,       user: network_policy}
    network_connectivity: {name: network_connectivity, user: network_connectivity}
    locket:               {name: locket,               user: locket}
    credhub:              {name: credhub,              user: credhub}

params:
  network: default

  base_domain: (( param "What is the base domain for this Cloud Foundry?" ))
  system_domain: (( concat "system." params.base_domain ))
  app_domains: (( grab meta.default_apps_domains meta.internal_app_domains ))
  apps_domain: (( grab params.app_domains[0] ))
  stemcell_os: ubuntu-jammy
  stemcell_version: latest

stemcells:
  - (( merge on alias ))
  - alias: default
    os: (( grab params.stemcell_os ))
    version: (( grab params.stemcell_version ))
