#!/bin/bash
set -eu
vault="secret/$GENESIS_VAULT_PREFIX"
target=$GENESIS_ENVIRONMENT


list() {
  echo "The following addons are defined:"
  echo
  echo "  login             Log into the Cloud Foundry instance as the"
  echo "                    admin user account.  This will overwrite local"
  echo "                    cf CLI configuration!"
  echo
  echo "  setup-cli         Installs cf CLI plugins like 'Targets', which"
  echo "                    helps to manage multiple Cloud Foundries from a"
  echo "                    single jumpbox."
  echo
  echo "  bind-autoscaler   Binds the Autoscaler service broker to your"
  echo "                    deployed CF. Only works if the autoscaler"
  echo "                    feature was enabled during deploy."
  echo
  echo "  asg               Generates application security group definitions,"
  echo "                    in JSON, which can then be fed into Cloud Foundry."
  echo
  echo "  smoketest         Run the smoke tests errand on the first vm in the"
  echo "                    api instance group."
}


login() {
  if ! cf plugins | grep -q '^cf-targets'; then
    describe "#Y{The cf-targets plugin does not seem to be installed}"
        echo "Install it first, via 'genesis do $GENESIS_ENVIRONMENT -- setup-cli'"
    exit 1
  fi

  base=$(lookup params.base_domain)
  system_domain=$(lookup params.system_domain system.$base)
  api_url=https://api.$system_domain
  password=$(safe read $vault/admin_user:password)

  if want_feature self-signed; then
    cf api $api_url --skip-ssl-validation
  elif [[ "$(lookup params.skip_ssl_validation)" == "true" ]]; then
    cf api $api_url --skip-ssl-validation
  else
    cf api $api_url
  fi

  cf auth admin "$password"
  cf save-target -f $target
  echo ; echo
  cf target
}

cats() {
    base=$(lookup params.base_domain)
    system_domain=$(lookup params.system_domain system.$base)
    export API_URL=api.$system_domain
    export ADMIN_PASSWORD=$(safe read $vault/admin_user:password)
    export APP_DOMAINS_0=run.$base

    tmpdir=$(mktemp -d -t cats.XXXXXXXXXX)
    export CONFIG=${tmpdir}/config.json
    git clone https://github.com/cloudfoundry/cf-acceptance-tests ${tmpdir}
    case $RUN_CATS in
      include_container_networking)
        sed -i "s#include_security_groups:.*#include_security_groups: true#g"
        ;;

      include_deployments)
        sed -i "s#include_v3:.*#include_v3: true#g"
        ;;
      include_service_instance_sharing)
        sed -i "s#include_services:.*#include_services: true#g"
        ;;
      include_sso)
        sed -i "s#include_services:.*#include_services: true#g"
        ;;
      include_tasks)
        sed -i "s#include_v3:.*#include_v3: true#g"
        ;;
      include_zipkin)
        sed -i "s#include_routing:.*#include_routing: true#g"
        ;;
    esac
    sed -i "s#${RUN_CATS}:.*#${RUN_CATS}: true#g" manifests/cf/cats.yml
    spruce merge manifests/cf/cats.yml | spruce json | jq '.' > ${CONFIG}
    VERSION=$(spruce json manifests/cf/cats.yml | jq -r '.cats_version')

    pushd ${tmpdir}
    git checkout ${VERSION}
    git submodule update --init
    ./bin/test -v -nodes=8
}

case $GENESIS_ADDON_SCRIPT in
list)
  list
  exit 0
  ;;

login)
  login
  exit 0
  ;;


setup-cli)
  if ! cf list-plugin-repos | grep -q CF-Community; then
    describe 'Adding #G{Cloud Foundry Community} plugins repository...'
    cf add-plugin-repo CF-Community http://plugins.cloudfoundry.org
  fi
  if ! cf plugins | grep -q '^cf-targets'; then
    describe 'Installing the #C{cf-targets} plugin...'
    cf install-plugin -r CF-Community Targets
  fi
  cf plugins
  ;;

asg)
  echo "To allow Cloud Foundry application instances to contact"
  echo "other application instances via the CF gorouters:"
  echo
  lookup params.cf_public_ips '[]' | jq '.[] | { "destination": ., "protocol": "all" }' | jq -s
  echo
  echo "To allow Cloud Floundry application instances to contact"
  echo "the services networks (for consuming brokered services):"
  echo
  lookup params.app_services_networks '[]' | jq '.[] | { "destination": ., "protocol": "all" }' | jq -s
  echo
  ;;

bind-autoscaler)
  if [[ $(exodus autoscaler_enabled) != "1" ]]; then
    echo "This Genesis deployment does not have the Autoscaler feature."
    exit 1
  fi
  login
  username=$(safe read $vault/autoscaler/servicebroker_account:username)
  password=$(safe read $vault/autoscaler/servicebroker_account:password)
  base=$(exodus system_domain)
  url="autoscalerservicebroker.$base"
  if [[ $(exodus self-signed) == "1" ]]; then
    cf create-service-broker autoscaler $username $password http://$url
    echo "Successfully created the service broker."
    exit 0
  fi
  cf create-service-broker autoscaler $username $password https://$url
  echo "Successfully created the service broker."
  exit 0
  ;;

smoketest)
  $GENESIS_BOSH_COMMAND -e $BOSH_ENVIRONMENT -d $BOSH_DEPLOYMENT run-errand smoke_tests --instance uaa/first
  ;;
cats)
  cats
  exit 0
  ;;
*)
  echo "Unrecognized Cloud Foundry Genesis Kit addon."
  list
  exit 1
  ;;
esac
