#!/bin/bash

cc_ok=yes
# Cloud Config checks
if [[ -n "$GENESIS_CLOUD_CONFIG" ]] ; then
  for t in minimal small small-highmem; do
    cloud_config_needs vm_type "$t"
  done
  for t in 5GB 10GB 100GB ; do 
    cloud_config_needs disk_type "$t"
  done
  cloud_config_needs network "$(lookup params.network default)"

  # Check if there were any errors reported from the above checks.
  if check_cloud_config ; then
    describe "  cloud config [#G{OK}]"
  else
    describe "  cloud config [#R{FAILED}]"
    cc_ok=no
  fi
fi


# Runtime config checks
runtime_ok=yes

# Check for BOSH DNS
if [[ $(bosh rc | spruce json | jq -r '.addons[] | select(.name == "bosh-dns")') == "" ]]; then
  runtime_ok=no
  describe "  #R{Errors were found} in your runtime-config:"
  describe "    - #R{BOSH DNS is not in the runtime-config, which is required. Refer to}"
  describe "      #R{'genesis man $GENESIS_ENVIRONMENT' for more info.}"
  describe ""
fi

# Check if there were any errors reported from runtime config checks
if [[ "$runtime_ok" == "yes" ]]; then
  describe "  runtime config [#G{OK}]"
else
  describe "  runtime config [#R{FAILED}]"
fi

env_ok=yes
# Environment Parameter checks - none yet!

if [[ "$env_ok" == "yes" ]]; then
  describe "  environment files [#G{OK}]"
else
  describe "  environment files [#R{FAILED}]"
fi

if [[ "$env_ok" == "no" || "$cc_ok" == "no" || "$runtime_ok" == no ]] ; then
  exit 1
fi

