#!/bin/bash
set -eu
exodus_data="$(lookup --exodus .)"
system_domain="$(echo "$exodus_data" | jq -r '.system_domain // "system.\(.base_domain)"')"
api_domain="$(echo "$exodus_data" | jq -r '.api_domain // "api.\($system_domain)"' --arg system_domain "$system_domain")"
api_url=https://$api_domain
admin=$(exodus admin_username)
password=$(exodus admin_password)

      echo "cloud foundry api"
  describe "       url: #C{$api_url}"
  describe "  username: #M{$admin}"
  describe "  password: #G{$password}"

      echo
      curl -m5 -Lsk $api_url/v2/info | jq -Cr . | sed -e 's/^/  /'
