#!/bin/bash
set -eu

if [[ $GENESIS_DEPLOY_RC == 0 ]]; then

      echo; echo;
  describe "#M{$GENESIS_ENVIRONMENT} Cloud Foundry deployed!"
      echo
      echo "For details about the deployment, run"
      echo
  describe "  #G{$GENESIS_CALL_ENV info}"
      echo
      echo "To see a list of available addons, run"
      echo
  describe "  #G{$GENESIS_CALL_ENV do -- list}"
      echo
      echo "To set up your local cf CLI installation with useful plugins:"
      echo
  describe "  #G{$GENESIS_CALL_ENV do -- setup-cli}"
      echo
      echo "To log into Cloud Foundry, run"
      echo
  describe "  #G{$GENESIS_CALL_ENV do -- login}"
      echo

fi
