#!/bin/bash
set -eu

if [[ $GENESIS_DEPLOY_RC == 0 ]]
then
  describe \
    "" \
    "#M{$GENESIS_ENVIRONMENT} Cloud Foundry deployed!" \
    "" \
    "For details about the deployment, run" \
    "" \
    "  #G{$GENESIS_CALL_ENV info}" \
    ""  \
    "To see a list of available addons, run" \
    "" \
    "  #G{$GENESIS_CALL_ENV do -- list}" \
    "" \
    "To set up your local cf CLI installation with useful plugins:" \
    "" \
    "  #G{$GENESIS_CALL_ENV do -- setup-cli}" \
    "" \
    "To log into Cloud Foundry, run" \
    "" \
    "  #G{$GENESIS_CALL_ENV do -- login}" \
    ""
fi

exit 0
