---
meta:
  ocfp:
    env:
      scale: (( grab params.ocfp_env_scale || "dev" ))
      cloud: (( concat genesis.env "." genesis.type "." ))

    vault:
      config_prefix: (( grab params.ocfp_vault_config_prefix || "config/" ))
      config:        (( concat genesis.ocfp_config_mount genesis.ocfp_env ))

    certs:
      trusted:
        - (( append )) # Account for unexpected merge orders.
        - (( vault genesis.secrets_mount "certs/org:ca" )) # Organization CA, if exists
        - (( vault genesis.secrets_mount "certs/dbs:ca" )) # External Databases CA
        # TODO: Add Blacksmith Services CA here, add in blacksmith integration

    cf:
      fqdns:
        base:   (( vault meta.ocfp.vault.config "/fqdns:base" ))
        system: (( vault meta.ocfp.vault.config "/fqdns:system" ))
        apps:
        - (( vault meta.ocfp.vault.config "/fqdns:apps" ))

