---
meta:
  ocfp:
    env:
      cloud: (( concat genesis.env "." genesis.type "." ))

    vault:
      config:        (( grab genesis.ocfp_config_base ))

    cf:
      fqdns:
        base:   (( vault meta.ocfp.vault.config "/fqdns:base" ))
        system: (( vault meta.ocfp.vault.config "/fqdns:system" ))
        apps:
        - (( vault meta.ocfp.vault.config "/fqdns:apps" ))

