#!/bin/bash
set -eu
KIT=cf
SKIP_CLEAN=${SKIP_CLEAN:-"true"}
SKIP_CLEAN=${SKIP_FRESH:-"false"}
SKIP_SMOKE_TESTS=${SKIP_SMOKE_TESTS:-"false"}
SKIP_DEPLOY=${SKIP_DEPLOY:-"false"}

header() {
    echo
    echo "###############################################"
    echo
    echo $*
    echo
}

cleanup() {

	for deployment in "$@"; do
	    echo "> deleting ${deployment}"
	    $BOSH -n -d "${deployment}" delete-deployment --force

	    for disk in $($BOSH disks --orphaned | grep "${deployment}" | awk '{print $1}'); do
		echo "  - removing disk $disk"
		$BOSH -n delete-disk "$disk"
	    done
	done

}

header "Checking previous deployments on ${BOSH_ENVIRONMENT}..."
$BOSH deployments

header "Cleaning up from any previous deployments (if necessary)..."a

if [[ "$SKIP_FRESH" == "false" ]]; then
  cleanup ci-baseline-${KIT}
else
  echo "Skipping FRESH"
fi
# safe rm -rf secret/ci/baseline/${KIT}

if [[ "$SKIP_DEPLOY" == "false" ]]; then
  header "Deploying BASELINE environment to verify functionality..."
  cd dev
  # make sure hooks are executable before screaming at shipit for failing.
  genesis compile-kit --name $KIT -v 9.9.9 --force
  cd ..
  genesis add-secrets ci-baseline
  genesis deploy -y ci-baseline
  $BOSH -d ci-baseline-${KIT} instances --ps
fi

header "Validating BASELINE environment..."
if [[ "$SKIP_SMOKE_TESTS" == "false" ]]; then
    $BOSH -d ci-baseline-${KIT} run-errand smoke_tests --instance=uaa/first
else
    echo "Skipping smoke_tests"
fi

if [[ "$SKIP_CLEAN" == "false" ]]; then
  cleanup ci-baseline-${KIT}
else
  echo "Skipping CLEANUP"
fi
