#!/bin/bash
set -eu
KIT=cf
SKIP_CLEANUP=${SKIP_CLEANUP:-"false"}
SKIP_SMOKE_TESTS=${SKIP_SMOKE_TESTS:-"false"}
SKIP_CATS=${SKIP_CATS:-"false"}

header() {
    echo
    echo "###############################################"
    echo
    echo $*
    echo
}

cleanup() {
    if [[ "$SKIP_CLEANUP" == "false" ]]; then
	for deployment in "$@"; do
	    echo "> deleting ${deployment}"
	    $BOSH -n -d "${deployment}" delete-deployment

	    for disk in $($BOSH disks --orphaned | grep "${deployment}" | awk '{print $1}'); do
		echo "  - removing disk $disk"
		$BOSH -n delete-disk "$disk"
	    done
	done
    else
        echo "Skipping cleanup"
    fi
}

header "Checking previous deployments on ${BOSH_ENVIRONMENT}..."
$BOSH deployments

header "Cleaning up from any previous deployments (if necessary)..."
cleanup ci-baseline-${KIT}
# safe rm -rf secret/ci/baseline/${KIT}

header "Deploying BASELINE environment to verify functionality..."
cd dev
# make sure hooks are executable before screaming at shipit for failing.
genesis compile-kit --name $KIT -v 9.9.9 --force
cd ..
genesis add-secrets ci-baseline
genesis deploy -y ci-baseline
$BOSH -d ci-baseline-${KIT} instances --ps
genesis do ci-baseline asg

header "Validating BASELINE environment..."
if [[ "$SKIP_SMOKE_TESTS" == "false" ]]; then
    $BOSH -d ci-baseline-${KIT} run-errand smoke_tests --instance=uaa/first
else
    echo "Skipping smoke_tests"
fi

header "Running CATs against BASELINE environment..."

if [[ "$SKIP_CATS" == "false" ]]; then
    GOLANG_URL=https://buildpacks.cloudfoundry.org/dependencies/go/go1.13.8.linux-amd64-cflinuxfs3-40558d27.tgz
    GOLANG_SHA256=40558d2781509e3619d9cbf37f0d9430ce1fa50684196f66612cc3a48cbe87b6
    mkdir -p /goroot /gopath  && \
        curl $GOLANG_URL | \
            tar xzf - -C /goroot --strip-components=1 && \
        chown -R root /goroot /gopath

    export GOROOT=/goroot
    export GOPATH=/gopath
    export PATH=/goroot/bin:/gopath/bin:$PATH

    curl -L 'https://packages.cloudfoundry.org/stable?release=linux64-binary&version=6.49.0&source=github-rel' | \
        tar xzf - -C /tmp
    mv /tmp/cf /usr/local/bin/cf

    genesis do ci-baseline cats
else
    echo "Skipping CATs"
fi

cleanup ci-baseline-${KIT}
