instance_groups:
  - name: cell
    jobs:
    - name: silk-cni
      properties:
        dns_servers:
          - 169.254.0.2
    - name: garden
      properties:
        garden:
          network_plugin: /var/vcap/packages/runc-cni/bin/garden-external-networker
          network_plugin_extra_args: [--configFile=/var/vcap/jobs/garden-cni/config/adapter.json]
    - name: garden-cni
      properties:
        cni_config_dir: /var/vcap/jobs/silk-cni/config/cni
        cni_plugin_dir: /var/vcap/packages/silk-cni/bin
