---
meta:
  default:
    azs:
      - (( replace ))
      - z1

instance_groups:
  - name: nats
    vm_extensions:
      - (( append ))
      - nats_as

  - name: uaa
    vm_extensions:
      - (( append ))
      - uaa_as

  - name: api
    vm_extensions:
      - (( append ))
      - api_as

  - name: doppler
    vm_extensions:
      - (( append ))
      - doppler_as

  - name: loggregator_trafficcontroller
    vm_extensions:
      - (( append ))
      - loggregator_tc_as

  - name: router
    vm_extensions:
      - (( replace ))  # force replace to remove the cf-load-balanced vm extension
      - router_as

  - name: bbs
    vm_extensions:
      - (( append ))
      - bbs_as

  - name: diego
    vm_extensions:
      - (( append ))
      - diego_as

  - name: cell
    vm_extensions:
      - (( append ))
      - cell_as
    jobs:
    - name: rep
      properties:
        diego:
          rep:
            use_azure_fault_domains: true
