---
meta:
  cc:
    stacks:
      - (( insert before "cflinuxfs3" ))
      - name: cflinuxfs2
        description: Cloud Foundry Linux-based filesystem (Ubuntu 14.04)

    install_buildpacks:
      - (( prepend ))
      - { name: staticfile_buildpack,  package: staticfile-buildpack-cflinuxfs2  }
      - { name: java_buildpack,        package: java-buildpack-cflinuxfs2        }
      - { name: ruby_buildpack,        package: ruby-buildpack-cflinuxfs2        }
      - { name: dotnet_core_buildpack, package: dotnet-core-buildpack-cflinuxfs2 }
      - { name: nodejs_buildpack,      package: nodejs-buildpack-cflinuxfs2      }
      - { name: go_buildpack,          package: go-buildpack-cflinuxfs2          }
      - { name: python_buildpack,      package: python-buildpack-cflinuxfs2      }
      - { name: php_buildpack,         package: php-buildpack-cflinuxfs2         }
      - { name: binary_buildpack,      package: binary-buildpack-cflinuxfs2      }

releases:
  - name:    cflinuxfs2
    version: "1.286.0"
    url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/cflinuxfs2-release?v=" releases.cflinuxfs2.version ))
    sha1:    cbee634a14c42b7f9be48506f6a551960cac1652

instance_groups:
  - name: cell
    jobs:
      - name: rep
        properties:
          diego:
            rep:
              preloaded_rootfses:
                - (( prepend ))
                - cflinuxfs2:/var/vcap/packages/cflinuxfs2/rootfs.tar

      - (( insert before "cflinuxfs3-rootfs-setup" ))
      - name: cflinuxfs2-rootfs-setup
        release: cflinuxfs2
        properties:
          cflinuxfs2-rootfs:
            trusted_certs: (( join "\n" meta.trusted_cas params.trusted_cas ))
