---
params:
  api_instances: 3
  cc_worker_instances: 3
  credhub_instances: 3
  diego_api_instances: 3
  diego_cell_instances: 10
  doppler_instances: 3
  log_api_instances: 3
  log_cache_instances: 3
  nats_instances: 3
  router_instances: 3
  scheduler_instances: 3
  tcp_router_instances: 3
  uaa_instances: 3
  # windows_diego_cell_instances: 1
